<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
	<title>Samsung Galaxy Note 3 Neo - Full phone specifications</title>
	<meta http-equiv=Content-Type content="text/html; charset=iso-8859-1">
	<?=$this->headScript();?>
	<?=$this->headLink();?>
<link href="http://172.16.31.69/lucky/gsmarena/public/lib/css/gsmarena5.css?v=6" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
	<div id="wrapper">
		<?=$this->layout()->content;?>
	</div>
</body>
</html>