<script type="text/javascript">
$(function() {
	$("#compose").validate();
});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Tambah Content</h1>
	<div class="header_nav_links"><a href="/admin/content">Back to Daftar Content</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>Sub Category</label><?php echo "$this->enum";?><font color="red">*</font></p>	
		<p><label>Nama Sub Category</label>		<input class="required" type="text" id="content" autocomplete="disable" name="content" value="<?=$this->row->content;?>"  /> <font color="red">*</font></p>				
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/content" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>