<script type="text/javascript">
	function getStatistik() {
		url = "/admin/statistik/data/";
		jenis = $("#jenis").val();
		tahun = $("#tahun").val();
		bulan = $("#bulan").val();

		if (jenis == "") {
			alert("Anda belum memasukkan Jenis Statistik!");
		} else {
			$("#resultDiv").load(url,{'jenis': jenis, 'tahun': tahun, 'bulan': bulan});
		}
	}

	function getExport() {
		var resultDiv = $("#resultDiv").html();
		if (resultDiv == "") {
			alert("Anda belum menekan tombol Filter!");
		} else if (resultDiv == "Data tidak ditemukan!") {
			alert("Data export tidak ditemukan!");
		} else {
			jenis = $("#jenis").val();
			tahun = $("#tahun").val();
			bulan = $("#bulan").val();

			var w = window.open("/admin/statistik/export/jenis/" + jenis + "/tahun/" + tahun + "/bulan/" + bulan, "popup", "width=960, height=700, menubar=no, status=no, location=no, directories=no, copyhistory=no, scrollbars=yes");
			if (w && !w.closed)
				w.focus();
		}
	}
</script>

<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?>  Daftar Statistik</h1>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p>
			<label class="left" for="jenis">Jenis Statistik :</label>
			<select id="jenis" name="jenis">
				<option value="1">Statistik Per Bidang</option>
				<option value="2">Statistik Per Pemeriksaan</option>
				<option value="3">Statistik Per Bulan</option>
			</select>
		</p>
		<p>
			<label class="left" for="tahun">Tahun :</label>
			<select id="tahun" name="tahun">
				<?
				for($i=date('Y'); $i>=2012; $i--) {
					echo '<option value="' . $i . '">' . $i . '</option>';
				}
				?>
			</select>
		</p>
		<p>
			<label class="left" for="bulan">Bulan :</label>
			<select id="bulan" name="bulan">
				<?
				$arrBulan = array(
					"1" => "Januari",
					"2" => "Februari",
					"3" => "Maret",
					"4" => "April",
					"5" => "Mei",
					"6" => "Juni",
					"7" => "Juli",
					"8" => "Agustus",
					"9" => "September",
					"10" => "Oktober",
					"11" => "November",
					"12" => "Desember"
				);
				foreach($arrBulan as $key => $value) {
					echo '<option value="' . $key . '">' . $value . '</option>';
				}
				?>
			</select>
		</p>

		<p class="savecancel"><a href="#" class="UIbutton-small" onClick="getStatistik();"/>Filter</a>&nbsp;<a href="#" class="UIbutton-small" onClick="getExport();"/>Export</a>&nbsp;<a href="/admin/statistik/index" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>
<hr>
<div id="resultDiv" name="resultDiv"></div>