<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Sistem Informasi Pamdal - DPR RI</title>
<?=$this->headScript();?>
<?=$this->headLink();?>
</head>

<div id="dialog" title="Basic modal dialog"></div>

<?
$peran = Zend_Auth::getInstance()->getIdentity()->peran;
$username = Zend_Auth::getInstance()->getIdentity()->nama;
?>

<body>

<div id="container">
	<!-- header -->
   	<div id="header">
    	<div id="top"></div>
		<div id="nav-bar">        
			<div id="topnav-bar">
	    		<div id="topleft">
					<ul id="topnav">
						<li><a class="home" href="/admin"><img src="<?=$this->url_statik;?>/images/admin/logoapp-<?=$this->domain;?>.png"></a></a></li>
						<li></li>
					</ul>
				</div>
		        <div id="topright">
					<ul id="topnav">
						<li><a href="/login/logout">Log Out</a></li>
						<li id="help"><a href="http://portal.dpr.go.id">&nbsp;Portal&nbsp;</a></li>
					</ul>
				</div>
			</div>			
		</div>
	</div>
	<!-- header -->

	<!-- content -->
    <div id="content-container">
		<div id="left-block" class="left">
    		<div id="personal">
	    		<h4>
						Nama: <strong> <?=$username ?></strong>
					</h4>	    		
	    		<h4>
						Peran: <strong><?=$peran ?></strong>
					</h4>	    		
	      </div>
            <div id="content-left">        
				<div class="menu">
					<? if ($peran == "admin") { ?>
						<h1 id="project_tab" class="UI_Action_Bar">
							Data Referensi
						</h1>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Tipe Penghuni" class="tt_atas" href="/admin/tipe-penghuni/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/tipe-penghuni/index">Daftar Tipe Penghuni</a>
							</li>	
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Penghuni
						</h1>
						<ul>
							<?
							$TipePenghuniService = new TipePenghuniService();
							$rows = $TipePenghuniService->getAllData();
							foreach($rows as $row)
							{
								echo '<li>';
								if ($row->id > 4) {
									echo '<span class="action right timespan">
										<a title="Tambah Penghuni" class="tt_atas" href="/admin/penghuni/add/tipe/' . $row->id . '">
											<span class="add"></span>
										</a>
									</span>';
								}
								echo '<a href="/admin/penghuni/index/tipe/' . $row->id . '">Daftar ' . $row->tipe_penghuni . '</a>';
								echo '</li>';
							}
							?>
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Website
						</h1>
						<ul>
							<li>
								<span class="action right timespan">
									<a title="Tambah Pengumuman" class="tt_atas" href="/admin/pengumuman/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/pengumuman/index">Daftar Pengumuman</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Berita" class="tt_atas" href="/admin/berita/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/berita/index">Daftar Berita</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Regulasi" class="tt_atas" href="/admin/regulasi/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/regulasi/index">Daftar Regulasi</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Foto" class="tt_atas" href="/admin/foto/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/foto/index">Daftar Foto</a>
							</li>
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Transaksi
						</h1>
						<ul>
							<li>
								<a href="/admin/pengaduan/index">Daftar Pengaduan</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Kendaraan" class="tt_atas" href="/admin/kendaraan/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/kendaraan/index">Daftar Kendaraan</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Kehilangan" class="tt_atas" href="/admin/kehilangan/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/kehilangan/index">Daftar Kehilangan</a>
							</li>
						</ul>
					<? } elseif ($peran == "super") { ?>

					<? } elseif ($peran == "user") { ?>
						<h1 id="project_tab" class="UI_Action_Bar">
							Data Referensi
						</h1>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Tipe Penghuni" class="tt_atas" href="/admin/tipe-penghuni/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/tipe-penghuni/index">Daftar Tipe Penghuni</a>
							</li>	
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Penghuni
						</h1>
						<ul>
							<?
							$TipePenghuniService = new TipePenghuniService();
							$rows = $TipePenghuniService->getAllData();
							foreach($rows as $row)
							{
								echo '<li>';
								if ($row->id > 4) {
									echo '<span class="action right timespan">
										<a title="Tambah Penghuni" class="tt_atas" href="/admin/penghuni/add/tipe/' . $row->id . '">
											<span class="add"></span>
										</a>
									</span>';
								}
								echo '<a href="/admin/penghuni/index/tipe/' . $row->id . '">Daftar ' . $row->tipe_penghuni . '</a>';
								echo '</li>';
							}
							?>
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Website
						</h1>
						<ul>
							<li>
								<span class="action right timespan">
									<a title="Tambah Pengumuman" class="tt_atas" href="/admin/pengumuman/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/pengumuman/index">Daftar Pengumuman</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Berita" class="tt_atas" href="/admin/berita/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/berita/index">Daftar Berita</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Regulasi" class="tt_atas" href="/admin/regulasi/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/regulasi/index">Daftar Regulasi</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Foto" class="tt_atas" href="/admin/foto/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/foto/index">Daftar Foto</a>
							</li>
						</ul>

						<h1 id="project_tab" class="UI_Action_Bar">
							Data Transaksi
						</h1>
						<ul>
							<li>
								<a href="/admin/pengaduan/index">Daftar Pengaduan</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Kendaraan" class="tt_atas" href="/admin/kendaraan/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/kendaraan/index">Daftar Kendaraan</a>
							</li>
							<li>
								<span class="action right timespan">
									<a title="Tambah Kehilangan" class="tt_atas" href="/admin/kehilangan/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/kehilangan/index">Daftar Kehilangan</a>
							</li>
						</ul>

					<? } elseif ($peran == "viewer") { ?>
						
					<? } ?>	

					<!--<h1 id="project_tab" class="UI_Action_Bar">
						Data Laporan
					</h1>
					<ul>
						<li>
							<a href="/admin/laporan/index">Laporan</a>
						</li>
						<li>
							<a href="/admin/rekapitulasi/index">Rekapitulasi</a>
						</li>
						<li>
							<a href="/admin/statistik/index">Statistik</a>
						</li>
					</ul>-->
				</div>
			</div>        
        </div>

        <div id="content-block" class="left">
			<?=$this->layout()->content;?>
        </div>
    </div>
    <div style="clear: both;"></div>
	<!-- content -->

	<!-- footer -->
    <div id="footer">
		<div style="clear: both;"></div>
		<?=$this->copyright;?>
    </div>
	<!-- footer -->

</div>
</body>
</html>