<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Sistem Informasi Pamdal - DPR RI</title>
<?=$this->headScript();?>
<?=$this->headLink();?>
</head>

<div id="dialog" title="Basic modal dialog"></div>

<?
$peran = Zend_Auth::getInstance()->getIdentity()->peran;
$username = Zend_Auth::getInstance()->getIdentity()->nama;
?>

<body>

<div id="container">
	<!-- header -->
   	<div id="header">
    	<div id="top"></div>
		<div id="nav-bar">        
			<div id="topnav-bar">
	    		<div id="topleft">
					<ul id="topnav">
						<li><a class="home" href="/admin"><img src="<?=$this->url_statik;?>/images/admin/logoapp-<?=$this->domain;?>.png"></a></a></li>
						<li></li>
					</ul>
				</div>
		        <div id="topright">
					<ul id="topnav">
						<li><a href="/login/logout">Log Out</a></li>
						<li id="help"><a href="http://portal.dpr.go.id">&nbsp;Portal&nbsp;</a></li>
					</ul>
				</div>
			</div>			
		</div>
	</div>
	<!-- header -->

	<!-- content -->
    <div id="content-container">
		<div id="left-block" class="left">
    		<div id="personal">
	    		<h4>
						Nama: <strong> <?=$username ?></strong>
					</h4>	    		
	    		<h4>
						Peran: <strong><?=$peran ?></strong>
					</h4>	    		
	      </div>
            <div id="content-left">        
				<div class="menu">
					<? if ($peran == "admin") { ?>
						<h1 id="project_tab" class="UI_Action_Bar">
							Data Basic
						</h1>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Brand" class="tt_atas" href="/admin/brand/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/brand/index">Daftar Brand</a>
							</li>	
						</ul>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Tipe Penghuni" class="tt_atas" href="/admin/category/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/category/index">Daftar Category</a>
							</li>	
						</ul>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah SubCategory" class="tt_atas" href="/admin/SubCategory/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/subcategory/index">Daftar SubCategory</a>
							</li>	
						</ul>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah SubCategoryContent" class="tt_atas" href="/admin/subcategorycontent/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/subcategorycontent/index">Daftar SubCategoryContent</a>
							</li>	
						</ul>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Content" class="tt_atas" href="/admin/content/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/content/index">Daftar Content</a>
							</li>	
						</ul>
						<h1 id="project_tab" class="UI_Action_Bar">
							Data Input 
						</h1>
						<ul>				
							<li>
								<span class="action right timespan">
									<a title="Tambah Type HP" class="tt_atas" href="/admin/type/add">
										<span class="add"></span>
									</a>
								</span>
								<a href="/admin/type/index">Daftar Type HP</a>
							</li>	
						</ul>

						<!---<h1 id="project_tab" class="UI_Action_Bar">
							Data Penghuni
						</h1>--->
					<? } elseif ($peran == "viewer") { ?>
						
					<? } ?>	
				</div>
			</div>        
        </div>

        <div id="content-block" class="left">
			<?=$this->layout()->content;?>
        </div>
    </div>
    <div style="clear: both;"></div>
	<!-- content -->

	<!-- footer -->
    <div id="footer">
		<div style="clear: both;"></div>
		<?=$this->copyright;?>
    </div>
	<!-- footer -->

</div>
</body>
</html>