 <?	
 // $this->SubCategoryService = new SubCategoryService();
 // $this->SubCategoryContentService = new SubCategoryContentService();
 // $this->TypeSpecService = new TypeSpecService();
 // foreach ($this->rowsCategory as $valueCategory) {
 // 	echo $valueCategory->category.'<br>';
 // 	$rowsSubCategory = $this->SubCategoryService->getDataWhereIdCategory($valueCategory->id_category);


 // 	foreach ($rowsSubCategory as $valueSubCategory) {
 // 		echo '-- '.$valueSubCategory->sub_category.'<br>';
 // 		$rowsSubCategoryContent = $this->SubCategoryContentService->getDataWhereIdSubCategory($valueSubCategory->id_sub_category);
 // 		foreach ($rowsSubCategoryContent as $valueSubCategoryContent) {
 // 			// echo '****'.$valueSubCategoryContent->id.'<br>';
 // 			 $rowsContent = $this->TypeSpecService->getAllDataContent(4, $valueSubCategoryContent->id);
 // 			 echo '**** ';
 // 			 foreach ($rowsContent as $valueContent) {
 // 			 	echo $valueContent->content;
 // 			 }
 // 			 echo '<br>';
 // 		}
 // 	}
 // }
 // die();
 ?>
<script type="text/javascript" language="javascript">
AUTOCOMPLETE_LIST_URL = "/quicksearch-6226.jpg";
</script>
<script language='JavaScript' type='text/javascript'>
function phpads_deliverActiveX(content)
{
	document.write(content);	
}
</script>
<div id="header">
	<div id="logo">
    	<a href="/"><span>GSMArena.com</span></a>
    </div>
	<div id="nav">
    	<ul id="menu">
        	<li><a href="/">Home</a></li>
        	<li><a href="news.php3">News</a></li>
        	<li><a href="reviews.php3">Reviews</a></li>
        	<li><a href="http://blog.gsmarena.com" target="_blank">Blog</a></li>
			<li><a href="tools.php3">Tools</a></li>			
        	<li><a href="compare.php3">Compare</a></li>
        	<li><a href="glossary.php3">Glossary</a></li>
        	<li><a href="faq.php3">FAQ</a></li>
        	<li><a href="contact.php3">Contact us</a></li>
        </ul>
        <form action="results.php3" method="get" id="topsearch">
            <input type="hidden" name="sQuickSearch" value="yes">
            <input type="text" onfocus="if(this.value=='Search')this.value='';autocompleteLoadList(AUTOCOMPLETE_LIST_URL);" value="Search" tabindex="201" accesskey="s" id="topsearch-text" name="sName" />
            <input type="submit" value="Go" id="quick-search-button" />
        </form>
    </div>
    
</div>
<div id="outer">
<div id="subHeader"> 
</div>
<br class="clear" />


<div id="body" class="resize">
<div id="main">
<div id="ttl" class="brand">
<h1>Samsung Galaxy Note 3 Neo</h1>
<p><a href="samsung-phones-9.php"><img src="http://cdn2.gsmarena.com/vv/logos/lg_samsu.gif" alt="Samsung" /></a></p>
</div>
<div id="specs-info">
<div id="specs-cp" class="box s2">
<div id="specs-cp-pic">
<a href=samsung_galaxy_note_3_neo-pictures-5961.php><img alt="Samsung Galaxy Note 3 Neo
MORE PICTURES" src=http://cdn2.gsmarena.com/vv/bigpic/-samsung-galaxy-note-3-neo-new1.jpg></a>
</div>
<ul>
<li class="specs-cp-review"><a href=samsung_galaxy_note_3_neo-review-1038.php><strong>Samsung Galaxy Note 3 Neo review: Neoclassic</strong></a></li><li id="specs-cp-read" title="Samsung Galaxy Note 3 Neo user reviews and opinions"><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Read opinions</a></li>
<li id="specs-cp-compare"><a href=compare.php3?idPhone1=5961>Compare</a></li>
 
<li id="specs-cp-pics"><a href=samsung_galaxy_note_3_neo-pictures-5961.php>Pictures</a></li>

<li id="specs-cp-spin"><a href=samsung_galaxy_note_3_neo-3d-spin-5961.php>360&deg; view</a></li>

<li id="specs-cp-related"><a href=related.php3?idPhone=5961>Related phones</a></li>

<li id="specs-cp-news"><a href="news.php3?idPhoneSearch=5961">In the news <font color="red">&nbsp;(new)</font></a></li>

							
</ul>
</div>
<div id="specs-buyhere" class="box s1 grad">
<h2><span>Check Price</span></h2>
<ul>
<li><a href=http://a.gsmarena.com/adclick.php?bannerid=60&zoneid=9&source=&dest=http%3A%2F%2Fwelectronics.com%2Fgsm%2Fsamsung%2FSamsung-Note3-Neo-SM-N750.html target=_blank>WElectronics</a></li></ul>
</div>
				
<div id="vote" class="box s2 nograd">	
<h2><span>Popularity</span></h2>
<div class="block" style="overflow: hidden;">
<dl id="vote-grph">

<dt>Daily interest</dt>
<dd id="vote-grph-popularity">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="16" /></span>
<tt>12%</tt>
</dd>
</dl>  
<dl id="vote-results"  class="borderTopY borderBottomN">
<dt>Total hits:</dt>
<dd>987487</dd>
</dl> 
</div>
</div>
<div id="vote" class="box s2 nograd">					
<h2><span>Voting results</span></h2>
<div class="block">
<dl id="vote-grph">
<dt>Design</dt>
<dd id="vote-grph-design">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
<dt>Features</dt>
<dd id="vote-grph-features">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
<dt>Performance</dt>
<dd id="vote-grph-performance">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
</dl>
<form method=post action="nickname.php3">
<input type=Hidden name=idPhone value="5961">
<div id="vote-rate">
<select name=nDesign id="vote-rate-design" title="Design"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option></select>
<select name=nFeatures id="vote-rate-features" title="Features"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option></select>
<select name=nPerformance id="vote-rate-performance" title="Performance"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
</select>
</div>

<div id="vote-submit">
<dl id="vote-resultsa" class="float-with-vote borderBottomN borderTopN">
    <dt>Votes:</dt>
    <dd>120</dd>
</dl>
<span class="submit"><input type="submit" value="Login" /></span>
<br class="clear" />
</div>
</form>
</div>
</div>			

<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.gsmarena.com%2Fsamsung_galaxy_note_3_neo-5961.php&amp;layout=button_count&amp;show_faces=true&amp;width=82&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:82px; height:21px;" allowTransparency="true">
</iframe>
<style type="text/css">#___plusone_0 { width: 83px !important; } </style><g:plusone size="medium"></g:plusone>

</div>
<div id="content-container">
<script language="JavaScript">
<!--
function helpW( strURL )
{
window.open( 'help.php3?term=' + strURL, '_blank', 'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=350,height=310' );
}
//-->
</script>

<div id="specs-list">
<?
 $this->SubCategoryService = new SubCategoryService();
 $this->SubCategoryContentService = new SubCategoryContentService();
 $this->TypeSpecService = new TypeSpecService();
 foreach ($this->rowsCategory as $valueCategory) {
 	$rowsSubCategory = $this->SubCategoryService->getDataWhereIdCategory($valueCategory->id_category);
 	$rowspan = 0;
 	foreach ($rowsSubCategory as $valueSubCategory) {
 		$rowspan++;
 	}
 	echo '<table cellspacing="0">
			<th rowspan="'.$rowspan.'" scope="row">'
			.$valueCategory->category.
			'</th>';
 	foreach ($rowsSubCategory as $valueSubCategory) {
 		echo '<tr>';
 		echo '<td class="ttl">'.$valueSubCategory->sub_category.'</td>';
 		$rowsSubCategoryContent = $this->SubCategoryContentService->getDataWhereIdSubCategory($valueSubCategory->id_sub_category);
 		foreach ($rowsSubCategoryContent as $valueSubCategoryContent) {
 			 $rowsContent = $this->TypeSpecService->getAllDataContent(4, $valueSubCategoryContent->id);
	 		echo '<td class="nfo">';
	 		foreach ($rowsContent as $valueContent) {
	 			echo $valueContent->content;
	 		}
	 		echo '</td>';
 		}
 		echo '</tr>';
 	}
 	echo '</table>';
 }
?>
</div>
<p class="note"><strong>Disclaimer.</strong> We can not guarantee that the information on this page is 100% correct. <a href=# onClick="helpW('legal.htm');">Read more</a></p>
					
<div id="user-comments" class="box s3 nobg">
<h2><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Samsung Galaxy Note 3 Neo - user opinions and reviews</a></h2>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname"><b>anil kant</b></li>
</ul>
<p class="uopin">I used Note 3 Neo and must say that i have very good experience with it 
I can say that it is better than Note 2 in performance  and gaming 
i had note-2 previously which is best and out of class phablet till today 
Only one thing is bad in Note 3...</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3896672">Reply</a></span></li>		

<li class="upost">2014-03-18 11:23</li>

<li class="ulocation">
<span title="Encoded location">uwVc</span></li>

<li class="utype"><span title="Type: Hands-on experience / review">
H</span>
</li>
</ul>
</div>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname2">fadil</li>
</ul>
<p class="uopin">after i upgrade version 4.4.2 my phone hang. cannot sync samsung account. many time my phone auto restart. like a shit!!</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3896609">Reply</a></span></li>		

<li class="upost">2014-03-18 10:44</li>

<li class="ulocation">
<span title="Encoded location">HjBC</span></li>

<li class="utype"><span title="Type: Hands-on experience / review">
H</span>
</li>
</ul>
</div>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname"><b>er.rohit</b></li>
</ul>
<p class="uopin">I used it from last 10 days it's battery backup is great. Amazing S pen Command.</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3894834">Reply</a></span></li>		

<li class="upost">2014-03-17 06:34</li>

<li class="ulocation">
<span title="Encoded location">n1H7</span></li>

<li class="utype"><span title="Type: Undefined">
U</span>
</li>
</ul>
</div>
		
<div class="sub-footer">
<div class="button-links">
<ul>
								
<li><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Read all opinions</a></li>
<li><a href="postopinion.php3?idPhone=5961">Post your opinion</a></li>
</ul>

</div>
<div id="opinions-total">Total user opinions: <b>182</b></div>
<br class="clear" />
									
						</div>
						
</div>

</div>
</div>
<div id="side">
<div id="side-top">
<div id="side-left">
</div>
<div id="side-right">
<div class="adr">
</div>
<br class="clear" />
</div>
</div>
</div>
</div>
<div id="brandmenu">
<ul>
<? foreach($this->rowsBrand as $value) {
	echo '<li><a href="#">'.$value->brand.'</a></li>';
}?>
<ul>
<li class="on"><a href="samsung-phones-9.php">Sub Menu</a></li>
</ul>
<p id="brandmenu-all-brands" class="more-buttons" title="More brands"><a href="makers.php3">All Brands</a></p>
<p id="brandmenu-rumor-mill" class="more-buttons"><a href="rumored.php3">Rumor Mill</a></p>
<p id="brandmenu-phone-finder" class="more-buttons"><a href="finder">Phone Finder</a></p>
</div><br class="clear" />
</div>
<div id="footer">
 <div class="footer-logo">
     <img src="http://cdn2.gsmarena.com/w/css/logo-gsmarena-com.gif" alt="" />
    </div>
<div id="footmenu">
<p>
<a href="/">Home</a>
<a href="news.php3">News</a>
<a href="reviews.php3">Reviews</a>
<a href="http://blog.gsmarena.com/">Blog</a>
<a href="compare.php3">Compare</a>
<a href="network-bands.php3">Coverage</a>
<a href="glossary.php3">Glossary</a>
<a href="faq.php3">FAQ</a>
<a href="links.php3">Links</a>

<a href="rss-news-reviews.php3" class="rss-icon">RSS feed</a></li>
<a target="_blank" href="http://www.facebook.com/pages/GSMArenacom/189627474421?sk=wall&amp;filter=2" class="fb-icon">Facebook</a>
<a target="_blank" href="http://twitter.com/gsmarena_com" class="tw-icon">Twitter</a>

</p>
<p>
&copy; 2000-2014 <a href="team.php3">GSMArena.com</a> 
<a href="http://www.gsmarena.com/switch.php3?ver=mobile&ref=GO8yaob8qKYryE1LYYYT7rfmWiMIOmVVNgPUxOaRpFzLXHcViQLPKqQL9I4YUfObStpShCouUb%2BgqLhio1SgvA%3D%3D">Mobile version</a>
<a href="contact.php3">Contact us</a>
<a href="advert.php3">Advertising</a>
<a href="privacy.php3">Privacy</a> 
<a href="terms.php3">Terms of use</a>			
</p>			
<div id="cdn-hosting">
<a href="http://www.maxcdn.com/" target="_blank">
  <span class="center">CDN by</span><br />
  <img src="http://cdn2.gsmarena.com/w/css/maxcdn.gif" alt="" />
</a>
</div>
</div>
 </div>

