<script type="text/javascript">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Daftar Berita</h1>
	<div class="header_nav_links">
		<span class="right context_menu"><a href="/admin/berita/add" class="UIlink-button small right">Tambah Berita</a></span>
	</div>
</div>
<div class="clear"></div>
<br>
<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>

	<table class="tablesorter">
		<thead>
			<tr>
				<th align="center" width="40">No.</th>
				<th align="center">Judul</th>
				<th align="center">Tanggal Kirim</th>
				<th align="center">Log Akses</th>
				<th align="center">Aksi</th>
			</tr>
		</thead>
		<tbody>
		<?php
			$indeks = 1;
			foreach($this->rows as $row) 
			{
				echo '<tr>';
				echo '<td align="center">'.$indeks.'.</td>';
				echo '<td>'.$row->judul . '</td>';
				echo '<td align="center">'.$this->FormatDate($row->tanggal, '%d-%m-%Y %H:%M') . '</td>';
				echo '<td align="center">'.$row->user_update . '</td>';
				echo '<td align="center"><a href="/admin/berita/edit/id/'.$row->id.'">EDIT</a>';
				if ($this->getRole() == 'admin' || $this->getRole() == 'super') {
					echo '&nbsp;|&nbsp;<a href="/admin/berita/delete/id/'.$row->id.'" onclick="return confirmDelete();">DELETE</a>';
				}
				echo "</td>";
				echo '</tr>';

				$indeks++;
			}
		?>
		
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>