<script type="text/javascript">
$(function() {
	$("#compose").validate();
});
</script>

<div class="content-header"></div>
<div class="UI_Header_Title">
	<h1><?=$this->avatar;?>  Tambah Merk Hp</h1>
	<div class="header_nav_links"><a href="/admin/type">Back to Daftar Merk Hp</a></div>
</div>
<div class="clear"></div>
<form id="compose" name="compose" method="post" action="" enctype="multipart/form-data">
	<div class="tabular">
		<p><label>Nama Brand</label><?php echo "$this->enum";?><font color="red">*</font></p>	
		<p><label>Nama Merk Hp</label>		<input class="required" type="text" id="type" autocomplete="disable" name="type" value="<?=$this->row->type;?>"  /> <font color="red">*</font></p>				
		<p class="savecancel"><label class="UIbutton-small"><input type="submit" value="Simpan" class=""/></label><a href="/admin/type" class="UIbutton-small">Batal</a></p>
	</div>
</form>
<div style="clear:both"></div>