<script type="text/javascript">
$(function(){
	$("table")
		.tablesorter({theme: 'blue', widthFixed: true, widgets: ['zebra', 'filter']})
		.tablesorterPager({container: $(".pager"), 
							output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', 
							fixedHeight: true, 
							removeRows: false, 
							cssGoto: '.gotoPage' });
});
</script>
<div class="content-header"></div>
	<div class="UI_Header_Title">
		<h1><?=$this->avatar;?>  Daftar Merk Hp</h1>
		<div class="header_nav_links"><span class="right context_menu"><a href="/admin/type/add" class="UIlink-button small right">Tambah Merk Hp</a></span>
	</div>
</div>
<div class="clear"></div>
<br>
<? if (count($this->rows) > 0) { ?>
	<?=$this->pager;?>
	<table cellspacing="1" cellpadding="6" width=100% class="tablesorter">
		<thead>
			<tr>
				<th align="center" width="5px"> </th>
				<th align="center">Merk HP</th>
				<th align="center">Tanggal</th>
				<td class="top" align="center" width="40px">Aktif</td>
				<td class="top" align="center"></td>				
			</tr>
		</thead>
		<tbody>
		<?php
			$i = 1;
			foreach($this->rows as $row) 
			{
				//$status = ($row->status == 1) ? "checked" : "";
				echo '<tr>';
				echo '<td>'.$i++.'</td>';
				echo '<td>'.$row->type.'</td>';
				//echo '<td>'.$row->type.'</td>';
				echo '<td>'.$this->FormatDate($row->tanggal_update).'</td>';
				echo '<td align="center">'.$this->GetStatus($row->status).'</td>';
				echo '<td><div align="center">';
				echo '<a href="/admin/type/edit/id/'.$row->id_type.'/id_brand/'.$row->id_brand.'" >EDIT</a>';
				echo ' | ';
				echo '<a href="/admin/type/delete/id/'.$row->id_type.'" onclick="return confirmDelete();">DELETE</a>';
				echo '</div></td></tr>';
			}
		?>		
		</tbody>
	</table>
<? } else {
	echo 'Data tidak ditemukan.';
}
?>