
<script type="text/javascript" language="javascript">
AUTOCOMPLETE_LIST_URL = "/quicksearch-6226.jpg";
</script>
<script language='JavaScript' type='text/javascript'>
function phpads_deliverActiveX(content)
{
	document.write(content);	
}
</script>

<div id="header">
	<div id="logo">
    	<a href="/"><span>GSMArena.com</span></a>
    </div>
	<div id="nav">
    	<ul id="menu">
        	<li><a href="/">Home</a></li>
        	<li><a href="news.php3">News</a></li>
        	<li><a href="reviews.php3">Reviews</a></li>
        	<li><a href="http://blog.gsmarena.com" target="_blank">Blog</a></li>
			<li><a href="tools.php3">Tools</a></li>			
        	<li><a href="compare.php3">Compare</a></li>
        	<li><a href="glossary.php3">Glossary</a></li>
        	<li><a href="faq.php3">FAQ</a></li>
        	<li><a href="contact.php3">Contact us</a></li>
        </ul>
        <form action="results.php3" method="get" id="topsearch">
            <input type="hidden" name="sQuickSearch" value="yes">
            <input type="text" onfocus="if(this.value=='Search')this.value='';autocompleteLoadList(AUTOCOMPLETE_LIST_URL);" value="Search" tabindex="201" accesskey="s" id="topsearch-text" name="sName" />
            <input type="submit" value="Go" id="quick-search-button" />
        </form>
    </div>
    
</div>
<div id="outer">
<div id="subHeader"> 
</div>
<br class="clear" />


<div id="body" class="resize">
<div id="main">
<div id="ttl" class="brand">
<h1>Samsung Galaxy Note 3 Neo</h1>
<p><a href="samsung-phones-9.php"><img src="http://cdn2.gsmarena.com/vv/logos/lg_samsu.gif" alt="Samsung" /></a></p>
</div>
<div id="specs-info">
<div id="specs-cp" class="box s2">
<div id="specs-cp-pic">
<a href=samsung_galaxy_note_3_neo-pictures-5961.php><img alt="Samsung Galaxy Note 3 Neo
MORE PICTURES" src=http://cdn2.gsmarena.com/vv/bigpic/-samsung-galaxy-note-3-neo-new1.jpg></a>
</div>
<ul>
<li class="specs-cp-review"><a href=samsung_galaxy_note_3_neo-review-1038.php><strong>Samsung Galaxy Note 3 Neo review: Neoclassic</strong></a></li><li id="specs-cp-read" title="Samsung Galaxy Note 3 Neo user reviews and opinions"><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Read opinions</a></li>
<li id="specs-cp-compare"><a href=compare.php3?idPhone1=5961>Compare</a></li>
 
<li id="specs-cp-pics"><a href=samsung_galaxy_note_3_neo-pictures-5961.php>Pictures</a></li>

<li id="specs-cp-spin"><a href=samsung_galaxy_note_3_neo-3d-spin-5961.php>360&deg; view</a></li>

<li id="specs-cp-related"><a href=related.php3?idPhone=5961>Related phones</a></li>

<li id="specs-cp-news"><a href="news.php3?idPhoneSearch=5961">In the news <font color="red">&nbsp;(new)</font></a></li>

							
</ul>
</div>
<div id="specs-buyhere" class="box s1 grad">
<h2><span>Check Price</span></h2>
<ul>
<li><a href=http://a.gsmarena.com/adclick.php?bannerid=60&zoneid=9&source=&dest=http%3A%2F%2Fwelectronics.com%2Fgsm%2Fsamsung%2FSamsung-Note3-Neo-SM-N750.html target=_blank>WElectronics</a></li></ul>
</div>
				
<div id="vote" class="box s2 nograd">	
<h2><span>Popularity</span></h2>
<div class="block" style="overflow: hidden;">
<dl id="vote-grph">

<dt>Daily interest</dt>
<dd id="vote-grph-popularity">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="16" /></span>
<tt>12%</tt>
</dd>
</dl>  
<dl id="vote-results"  class="borderTopY borderBottomN">
<dt>Total hits:</dt>
<dd>987487</dd>
</dl> 
</div>
</div>
<div id="vote" class="box s2 nograd">					
<h2><span>Voting results</span></h2>
<div class="block">
<dl id="vote-grph">
<dt>Design</dt>
<dd id="vote-grph-design">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
<dt>Features</dt>
<dd id="vote-grph-features">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
<dt>Performance</dt>
<dd id="vote-grph-performance">
<span><img src="http://cdn2.gsmarena.com/w/css/spacer.gif" width="58" /></span>
<tt>4.9</tt>
</dd>
</dl>
<form method=post action="nickname.php3">
<input type=Hidden name=idPhone value="5961">
<div id="vote-rate">
<select name=nDesign id="vote-rate-design" title="Design"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option></select>
<select name=nFeatures id="vote-rate-features" title="Features"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option></select>
<select name=nPerformance id="vote-rate-performance" title="Performance"><option>1</option><option>2</option><option>3</option><option>4</option><option selected>5</option><option>6</option><option>7</option><option>8</option><option>9</option><option>10</option>
</select>
</div>

<div id="vote-submit">
<dl id="vote-resultsa" class="float-with-vote borderBottomN borderTopN">
    <dt>Votes:</dt>
    <dd>120</dd>
</dl>
<span class="submit"><input type="submit" value="Login" /></span>
<br class="clear" />
</div>
</form>
</div>
</div>			

<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.gsmarena.com%2Fsamsung_galaxy_note_3_neo-5961.php&amp;layout=button_count&amp;show_faces=true&amp;width=82&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:82px; height:21px;" allowTransparency="true">
</iframe>
<style type="text/css">#___plusone_0 { width: 83px !important; } </style><g:plusone size="medium"></g:plusone>

</div>
<div id="content-container">
<script language="JavaScript">
<!--
function helpW( strURL )
{
window.open( 'help.php3?term=' + strURL, '_blank', 'toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=no,width=350,height=310' );
}
//-->
</script>

<div id="specs-list">
					
<table cellspacing="0">
<tr>
	<th rowspan="7" scope="row">
	General
	</th>
	<td class="ttl">
		<a href="network-bands.php3">2G Network</a>
	</td>
	<td class="nfo">GSM 850 / 900 / 1800 / 1900 - all versions</td>
</tr>
<tr>
	<td class="ttl">
		<a href="network-bands.php3">3G Network</a>
	</td>
	<td class="nfo">HSDPA 850 / 900 / 1900 / 2100 - SM-N7505</td>
</tr>
<tr>
	<td class="ttl">&nbsp;</td>
	<td class="nfo">HSDPA 900 / 1900 / 2100 - SM-N750</td>
</tr>
<tr>
<td class="ttl"><a href="network-bands.php3">4G Network</a></td>
<td class="nfo">LTE 800 / 850 / 900 / 1800 / 2100 / 2600 - SM-N7505</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=sim">SIM</a></td>
<td class="nfo">Micro-SIM</td>
</tr><tr>
<td class="ttl"><a href=# onClick="helpW('h_year.htm');">Announced</a></td>
<td class="nfo">2014, January</td>
</tr>
<tr>
<td class="ttl"><a href=# onClick="helpW('h_status.htm');">Status</a></td>
<td class="nfo">Available. Released 2014, February</td>
</tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="3" scope="row">Body</th>
<td class="ttl"><a href=# onClick="helpW('h_dimens.htm');">Dimensions</a></td>
<td class="nfo">148.4 x 77.4 x 8.6 mm (5.84 x 3.05 x 0.34 in)</td>
</tr><tr>
<td class="ttl"><a href=# onClick="helpW('h_weight.htm');">Weight</a></td>
<td class="nfo">162.5 g (5.71 oz)</td>
</tr>
<tr><td class="ttl">&nbsp;</td><td class="nfo">- S Pen stylus</td></tr>
		
</table>
<table cellspacing="0">
<tr>
<th rowspan="4" scope="row">Display</th>
<td class="ttl"><a href="glossary.php3?term=display-type">Type</a></td>
<td class="nfo">Super AMOLED capacitive touchscreen, 16M colors</td>
</tr><tr>
<td class="ttl"><a href=# onClick="helpW('h_dsize.htm');">Size</a></td>
<td class="nfo">720 x 1280 pixels, 5.5 inches (~267 ppi pixel density)</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=multitouch">Multitouch</a></td>
<td class="nfo">Yes</td>
</tr>
<tr><td class="ttl">&nbsp;</td><td class="nfo">- TouchWiz UI<br />
</td></tr>
		

</table>
<table cellspacing="0">
<tr>
<th rowspan="3" scope="row">Sound</th>
<td class="ttl"><a href="glossary.php3?term=call-alerts">Alert types</a></td>
<td class="nfo">Vibration; MP3, WAV ringtones</td>
	</tr>
	
<tr>
<td class="ttl"><a href="glossary.php3?term=loudspeaker">Loudspeaker</a> </td>
<td class="nfo">Yes</td>
</tr>

<tr>
<td class="ttl"><a href="glossary.php3?term=audio-jack">3.5mm jack</a> </td>
<td class="nfo">Yes</td>
</tr>
	

	
</table>
<table cellspacing="0">
<tr>
<th rowspan="2" scope="row">Memory</th>
<td class="ttl"><a href="glossary.php3?term=memory-card-slot">Card slot</a></td>
<td class="nfo">microSD, up to 64 GB</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=dynamic-memory">Internal</a></td>
<td class="nfo">16 GB (11 GB user available), 2 GB RAM</td>
</tr>		
</table>
<table cellspacing="0">
<tr>
<th rowspan="10" scope="row">Data</th>
<td class="ttl"><a href="glossary.php3?term=gprs">GPRS</a></td>
<td class="nfo">Yes</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=edge">EDGE</a></td>
<td class="nfo">Yes</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=3g">Speed</a></td>
<td class="nfo">HSDPA, 42 Mbps; LTE, Cat4, 50 Mbps UL, 150 Mbps DL (Neo LTE+)/ HSDPA, 21 Mbps (Neo 3G)</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=wi-fi">WLAN</a></td>
<td class="nfo">Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, DLNA, Wi-Fi hotspot</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=bluetooth">Bluetooth</a></td>
<td class="nfo">Yes, v4.0 with A2DP, LE</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=nfc">NFC</a></td>
<td class="nfo">Yes</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=irda">Infrared port</a></td>
<td class="nfo">Yes</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=usb">USB</a></td>
<td class="nfo">Yes, microUSB v2.0, USB Host</td>
</tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="4" scope="row">Camera</th>
<td class="ttl"><a href="glossary.php3?term=camera">Primary</a></td>
<td class="nfo">8 MP, 3264 x 2448 pixels, autofocus, LED flash, <a href="piccmp.php3?idType=1&idPhone1=5961&nSuggest=1">check quality</a></td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=camera">Features</a></td>
<td class="nfo">Geo-tagging, touch focus, face and smile detection, image stabilization, panorama, HDR</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=camera">Video</a></td>
<td class="nfo">Yes, 1080p@30fps, stereo sound rec., <a href="vidcmp.php3?idType=1&idPhone1=5961&nSuggest=1">check quality</a></td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=video-call">Secondary</a></td>
<td class="nfo">Yes, 2 MP, 1080p</td>
</tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="14" scope="row">Features</th>
<td class="ttl"><a href="glossary.php3?term=os">OS</a></td>
<td class="nfo">Android OS, v4.3 (Jelly Bean)</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=chipset">Chipset</a></td>
<td class="nfo">Exynos 5260</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=cpu">CPU</a></td>
<td class="nfo">Quad-core 1.3 GHz Cortex A7 & dual-core 1.7 GHz Cortex A15</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=gpu">GPU</a></td>
<td class="nfo">Mali-T624</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=sensors">Sensors</a></td>
<td class="nfo">Accelerometer, gyro, proximity, compass</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=messaging">Messaging</a></td>
<td class="nfo">SMS(threaded view), MMS, Email, Push Mail, IM, RSS</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=browser">Browser</a></td>
<td class="nfo">HTML5</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=fm-radio">Radio</a></td>
<td class="nfo">No</td>
</tr> 	
<tr>
<td class="ttl"><a href="glossary.php3?term=gps">GPS</a></td>
<td class="nfo">Yes, with A-GPS support and GLONASS</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=java">Java</a></td>
<td class="nfo">Yes, via Java MIDP emulator</td>
</tr>
<tr>
<td class="ttl"><a href=# onClick="helpW('h_colors.htm');">Colors</a></td>
<td class="nfo">Black, White, Green</td>
</tr>
<tr>
<td class="ttl">&nbsp;</td>
<td class="nfo">- S-Voice natural language commands and dictation<br />
- Air gestures<br />
- SNS integration<br />
- Active noise cancellation with dedicated mic<br />
- Dropbox (50 GB cloud storage)<br />
- MP4/WMV/H.264/H.263 player<br />
- MP3/WAV/eAAC+/FLAC player<br />
- Organizer<br />
- Image/video editor<br />
- Document viewer<br />
- Google Search, Maps, Gmail,<br />
YouTube, Calendar, Google Talk, Picasa<br />
- Voice memo/dial/commands<br />
- Predictive text input (Swype)</td></tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="4" scope="row">Battery</th>
<td class="ttl">&nbsp;</td>
<td class="nfo">Li-Ion 3100 mAh battery</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=stand-by-time">Stand-by</a></td>
<td class="nfo"> (2G) / Up to 540 h (3G)</td>
</tr><tr>
<td class="ttl"><a href="glossary.php3?term=talk-time">Talk time</a></td>
<td class="nfo"> (2G) / Up to 18 h (3G)</td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=music-playback-time">Music play</a></td>
<td class="nfo">Up to 64 h</td>
</tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="3" scope="row">Misc</th>
<td class="ttl"><a href="glossary.php3?term=sar">SAR US</a></td>
<td class="nfo">
0.54 W/kg (head) &nbsp; &nbsp; 0.70 W/kg (body) &nbsp; &nbsp; </td>
</tr>
<tr>
<td class="ttl"><a href="glossary.php3?term=sar">SAR EU</a></td>
<td class="nfo">
0.25 W/kg (head) &nbsp; &nbsp; 0.27 W/kg (body) &nbsp; &nbsp; </td>
</tr>
<tr>
<td class="ttl"><a href=# onClick="helpW('h_price.htm');">Price group</a></td>
<td class="nfo"><img src=http://cdn2.gsmarena.com/vv/price/pg8.gif title="About 410 EUR"></td>
</tr>
</table>
<table cellspacing="0">
<tr>
<th rowspan="5" scope="row">Tests</th>
<td class="ttl"><a href="gsmarena_lab_tests-review-751p2.php">Display</a></td>
<td class="nfo">
<a class="noUnd" href="http://www.gsmarena.com/samsung_galaxy_note_3_neo-review-1038p3.php">Contrast ratio: Infinite (nominal), 3.487 (sunlight)</a></td>
</tr>
<tr>
<td class="ttl"><a href="gsmarena_lab_tests-review-751p3.php">Loudspeaker</a></td>
<td class="nfo">
<a class="noUnd" href="http://www.gsmarena.com/samsung_galaxy_note_3_neo-review-1038p7.php">Voice 68dB / Noise 64dB / Ring 75dB</a></td>
</tr>
<tr>
<td class="ttl"><a href="gsmarena_lab_tests-review-751p4.php">Audio quality</a></td>
<td class="nfo">
<a class="noUnd" href="http://www.gsmarena.com/samsung_galaxy_note_3_neo-review-1038p8.php#aq">Noise -96.1dB / Crosstalk -94.9dB</a></td>
</tr>
<tr>
<td class="ttl"><a href="gsmarena_lab_tests-review-751p5.php">Camera</a></td>
<td class="nfo">
<a class="noUnd" href="piccmp.php3?idType=1&idPhone1=5961&nSuggest=1">Photo</a> / <a class="noUnd" href="vidcmp.php3?idType=1&idPhone1=5961&nSuggest=1">Video</a></td>
</tr>
<tr>
<td class="ttl"><a href="gsmarena_lab_tests-review-751p6.php">Battery life</a></td>
<td class="nfo">
<a class="noUnd" href="http://blog.gsmarena.com/samsung-galaxy-note-3-neo-battery-test/">Endurance rating 74h</a></td>
</tr>
<tr>
</tr>
</table>
</div>
<p class="note"><strong>Disclaimer.</strong> We can not guarantee that the information on this page is 100% correct. <a href=# onClick="helpW('legal.htm');">Read more</a></p>
					
<div id="user-comments" class="box s3 nobg">
<h2><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Samsung Galaxy Note 3 Neo - user opinions and reviews</a></h2>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname"><b>anil kant</b></li>
</ul>
<p class="uopin">I used Note 3 Neo and must say that i have very good experience with it 
I can say that it is better than Note 2 in performance  and gaming 
i had note-2 previously which is best and out of class phablet till today 
Only one thing is bad in Note 3...</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3896672">Reply</a></span></li>		

<li class="upost">2014-03-18 11:23</li>

<li class="ulocation">
<span title="Encoded location">uwVc</span></li>

<li class="utype"><span title="Type: Hands-on experience / review">
H</span>
</li>
</ul>
</div>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname2">fadil</li>
</ul>
<p class="uopin">after i upgrade version 4.4.2 my phone hang. cannot sync samsung account. many time my phone auto restart. like a shit!!</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3896609">Reply</a></span></li>		

<li class="upost">2014-03-18 10:44</li>

<li class="ulocation">
<span title="Encoded location">HjBC</span></li>

<li class="utype"><span title="Type: Hands-on experience / review">
H</span>
</li>
</ul>
</div>
						
<div class="user-thread">
<ul class="uinfo2"><li class="uname"><b>er.rohit</b></li>
</ul>
<p class="uopin">I used it from last 10 days it's battery backup is great. Amazing S pen Command.</p>
<ul class="uinfo">
<li class="ureply"><span title="Reply to this post"><a href="postopinion.php3?idPhone=5961&idOpinion=3894834">Reply</a></span></li>		

<li class="upost">2014-03-17 06:34</li>

<li class="ulocation">
<span title="Encoded location">n1H7</span></li>

<li class="utype"><span title="Type: Undefined">
U</span>
</li>
</ul>
</div>
		
<div class="sub-footer">
<div class="button-links">
<ul>
								
<li><a href="samsung_galaxy_note_3_neo-reviews-5961.php">Read all opinions</a></li>
<li><a href="postopinion.php3?idPhone=5961">Post your opinion</a></li>
</ul>

</div>
<div id="opinions-total">Total user opinions: <b>182</b></div>
<br class="clear" />
									
						</div>
						
</div>

</div>
</div>
<div id="side">
<div id="side-top">
<div id="side-left">
</div>
<div id="side-right">
<div class="adr">
</div>
<br class="clear" />
</div>
</div>
</div>
</div>
<div id="brandmenu">
<ul>
<?php foreach($this->rowsBrand as $value){
echo '<li><a href="#">'.$value->brand.'</a></li>';
}?>
<ul>
<li class="on"><a href="samsung-phones-9.php">Sub Menu</a></li>
</ul>
<p id="brandmenu-all-brands" class="more-buttons" title="More brands"><a href="makers.php3">All Brands</a></p>
<p id="brandmenu-rumor-mill" class="more-buttons"><a href="rumored.php3">Rumor Mill</a></p>
<p id="brandmenu-phone-finder" class="more-buttons"><a href="finder">Phone Finder</a></p>
</div><br class="clear" />
</div>
<div id="footer">
 <div class="footer-logo">
     <img src="http://cdn2.gsmarena.com/w/css/logo-gsmarena-com.gif" alt="" />
    </div>
<div id="footmenu">
<p>
<a href="/">Home</a>
<a href="news.php3">News</a>
<a href="reviews.php3">Reviews</a>
<a href="http://blog.gsmarena.com/">Blog</a>
<a href="compare.php3">Compare</a>
<a href="network-bands.php3">Coverage</a>
<a href="glossary.php3">Glossary</a>
<a href="faq.php3">FAQ</a>
<a href="links.php3">Links</a>

<a href="rss-news-reviews.php3" class="rss-icon">RSS feed</a></li>
<a target="_blank" href="http://www.facebook.com/pages/GSMArenacom/189627474421?sk=wall&amp;filter=2" class="fb-icon">Facebook</a>
<a target="_blank" href="http://twitter.com/gsmarena_com" class="tw-icon">Twitter</a>

</p>
<p>
&copy; 2000-2014 <a href="team.php3">GSMArena.com</a> 
<a href="http://www.gsmarena.com/switch.php3?ver=mobile&ref=GO8yaob8qKYryE1LYYYT7rfmWiMIOmVVNgPUxOaRpFzLXHcViQLPKqQL9I4YUfObStpShCouUb%2BgqLhio1SgvA%3D%3D">Mobile version</a>
<a href="contact.php3">Contact us</a>
<a href="advert.php3">Advertising</a>
<a href="privacy.php3">Privacy</a> 
<a href="terms.php3">Terms of use</a>			
</p>			
<div id="cdn-hosting">
<a href="http://www.maxcdn.com/" target="_blank">
  <span class="center">CDN by</span><br />
  <img src="http://cdn2.gsmarena.com/w/css/maxcdn.gif" alt="" />
</a>
</div>
</div>
 </div>